name: "provision stack build/ deploy for Azure app service"

on:
  workflow_dispatch:
   inputs:
    CREATE_AZURE_WEBAPP:
     required: true
  
env:
  AZURE_WEBAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: move the file
        run: |
          mv ./instance-contents/README.md ./README.md
          rm -r ./instance-contents
      
      - name: Commit files
        run: |
          git config --global user.name '${{github.actor}}'
          git config --global user.email '${{github.actor}}@users.noreply.github.com'
          git add -A
          git commit -m "Added readme."
          git push
          
      - name: use python
        uses: actions/setup-python@v2
        with:
          python-version: '3.*'
          
      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Collect static
        run: python manage.py collectstatic --noinput
    
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !venv/
  
  deploy-to-webapp:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}

      - name: Deploy to DigitalOcean Kubernetes
        run: doctl apps create --spec config/spec.yaml --wait
